### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by mulot35** [markomannux/pyproscenic#1]
Hello,
Do you have a tutorial to set up the call as well as a script.
I am under domoticz (free home automation) and I wish to communicate with my Proscenic.

Thank you.

Sorry for my english.

**Comment by markomannux** [comment]
Hi, I'm afraid this repo is only an early experiment. I didn't even push my code here...
Now I've updated it with what I've done but I don't even own a Proscenic any more.
It's in python since it's the language used in Home Assistant. I don't have any experience with domoticz so I don't know how portable it is.

The only hint I can give you is that you have to sniff UDP traffic in your network in order to get the serial number of your vacuum (you can use wireshark to do that; it can be a little tricky since you have to sniff the traffic from your proscenic app: something your phone won't allow so easily. I managed to do it installing the app on bluestacks). Otherwise you won't be able to issue any command.

I can also point you to [this repo](https://github.com/oskarn97/fhem-Proscenic) where there is a more structured approach (in PERL).

Hope this would help

**Comment by mulot35** [comment]
Hi, I had used "Burp suite (free)" with the phone.
I will add the emulator.
Thank you for your reply.
